In [94]:
import numpy as np
import pandas as pd

In [59]:
df = pd.read_csv('./CyYoungEligiblePitchers.csv')

In [60]:
# df[df['win'] == 2] # this is the outlier as he was in two leagues
df.loc[(df['player_id'] == 'sutclri01') & (df['year'] == 1984)]['win'] = 1

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [61]:
df = df.drop(['player_id', 'year'], axis=1)

In [62]:
df['win'] = df['win'].astype(int)

In [63]:
df

w   l   g  gs  cg  sho  sv  ipouts    h   er ...    so   ibb   wp  \
0       1   0  11   0   0    0   0    32.0   20    8 ...     5   0.0  0.0   
1       3   0  45   0   0    0   0   159.0   41   24 ...    49   0.0  1.0   
2       2   1  25   0   0    0   0    97.0   39   23 ...    36   3.0  2.0   
3       4   2  47   0   0    0   0   146.0   49   30 ...    49   2.0  3.0   
4       3   6  73   0   0    0  38   214.0   49   20 ...    80   3.0  2.0   
5       0   6  53   0   0    0  31   149.0   33   19 ...    49   5.0  2.0   
6       0   0   1   0   0    0   0     3.0    1    1 ...     1   0.0  0.0   
7       2   2  43   0   0    0   0   119.0   39   19 ...    36   6.0  1.0   
8       1   1  33   0   0    0   0    92.0   25   16 ...    35   3.0  1.0   
9       6   2  13  13   4    2   0   277.0   85   32 ...    49   1.0  0.0   
10     11   8  29  29   6    1   0   536.0  185   80 ...    93   4.0  3.0   
11      9  10  37  28   7    1   2   556.0  200   99 ...    96   7.0  5.0   
12      8  13  40  21   5    1   2   525.0  193   79 ...    74   3.0  2.0   
13      4   4  39   0   0    0  11   196.0   56   17 ...    38   2.0  1.0   
14      3   3  24   0   0    0   4   156.0   45   20 ...    40   2.0  2.0   
15      4   1  23   0   0    0   8   117.0   30    7 ...    28   5.0  0.0   
16     10   6  54   0   0    0  14   264.0   83   37 ...    67   7.0  0.0   
17      6   7  66   0   0    0  34   245.0   71   27 ...    67   2.0  4.0   
18      1   0   7   0   0    0   2    24.0    8    2 ...     3   0.0  0.0   
19      0   0  35   0   0    0   0   140.0   40   21 ...    28   5.0  1.0   
20      1   5  49   0   0    0   2   178.0   56   26 ...    34   3.0  0.0   
21      3   1  32   0   0    0   3   114.0   33   21 ...    24   4.0  3.0   
22      0   1  22   0   0    0   0    57.0   14    6 ...    12   0.0  0.0   
23      1   4  29   0   0    0   0    59.0   28   16 ...    15   0.0  0.0   
24      0   6  37   6   0    0   0   138.0   57   26 ...    38   1.0  4.0   
25      0   3  39   0   0    0   0   113.0   42   14 ...    32   0.0  0.0   
26      2   4  69   0   0    0   0   172.0   34   10 ...    51   3.0  0.0   
27      2   2  62   0   0    0   0   143.0   45   22 ...    45   3.0  4.0   
28      1   0   5   3   1    0   0    56.0   16    8 ...     6   0.0  0.0   
29      5   7  19  17   3    0   0   288.0   89   32 ...    38   3.0  3.0   
...    ..  ..  ..  ..  ..  ...  ..     ...  ...  ... ...   ...   ...  ...   
26930  12   8  32  32   0    0   0   587.0  186   64 ...   153   2.0  3.0   
26931  19   9  32  32   4    2   0   640.0  192   77 ...   161   0.0  3.0   
26932  14   5  32  32   3    2   0   599.0  185   59 ...   182   0.0  4.0   
26933  13  10  33  33   0    0   0   605.0  204   82 ...   164   3.0  2.0   
26934   0   0   1   1   0    0   0    13.0   11    8 ...     1   0.0  1.0   
26935   7   4  14  14   1    1   0   278.0   64   28 ...    78   2.0  2.0   
26936  17   8  35  35   3    2   0   643.0  184   83 ...   205   0.0  6.0   
26937  23   5  35  35   1    0   0   688.0  182   70 ...   182   2.0  2.0   
26938  14  12  35  35   4    1   0   695.0  186   85 ...   146   3.0  4.0   
26939  11  11  34  34   0    0   0   639.0  216  106 ...   163   2.0  4.0   
26940  14  13  35  35   0    0   0   685.0  185   98 ...   171   0.0  4.0   
26941  16  10  34  34   0    0   0   663.0  211   94 ...   151   5.0  4.0   
26942  11  13  34  33   0    0   0   590.0  182   99 ...   131   4.0  5.0   
26943  10  17  32  32   0    0   0   540.0  186  103 ...   120  10.0  3.0   
26944  10  13  33  33   1    0   0   576.0  179   86 ...   154   8.0  2.0   
26945   9  14  34  33   1    0   0   598.0  184   92 ...   150   7.0  7.0   
26946   3   4  13   9   0    0   0   161.0   51   35 ...    32   1.0  1.0   
26947  15   8  32  32   1    1   0   553.0  186   85 ...   114   6.0  1.0   
26948   5  11  30  25   0    0   0   400.0  173   85 ...    86   2.0  5.0   
26949   0   0   3   2   0    0   0    21.0   12    8 ...     2   0.0  0.0   
2695

In [84]:
df.columns

Index(['w', 'l', 'g', 'gs', 'cg', 'sho', 'sv', 'ipouts', 'h', 'er', 'hr', 'bb',
       'so', 'ibb', 'wp', 'hbp', 'bk', 'bfp', 'r', 'era', 'whip', 'win'],
      dtype='object')

In [64]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [73]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [74]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [75]:
y_pred = classifier.predict(X_test)

In [76]:
y_pred, y_test

(array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]))

In [77]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [78]:
cm

array([[5367,    7],
       [  10,    8]])

In [79]:
print('We have {} % accuracy'.format(cm.diagonal().sum() / cm.sum() * 100))

We have 99.68471810089021 % accuracy


In [92]:
# let's try to predict whether Clayton Kershaw had a Cy Young Award year
kershaw = np.array([18, 4, 27, 27, 1, 0, 0, 525.0, 136, 45, 23, 30, 202, 0, 4, 0, 2, 679, 49, 2.31, 0.949]).reshape(1, -1)
kershaw_predict = classifier.predict(kershaw)

In [93]:
kershaw_predict # wow it's right

array([0])